[project]
name = "wx-mcp"
version = "0.1.0"
description = "wxauto mcp server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "wxauto>=3.9.11.17.5",
]
